#!/usr/bin/env node
'use strict';
// Builds the standalone weekly-report page.
//
// The page runs the same lib/ modules the CLI does, wrapped in a tiny module
// registry, so the reporting rules exist in exactly one place and the node
// tests cover the browser build too. Only file reading differs: Node inflates
// an .xlsx with zlib, the browser with DecompressionStream.
//
//   node tools/build-html.js   ->   dist/weekly-report.html

const fs   = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
// Order matters only for readability; the registry resolves lazily.
const MODULES = ['zip', 'sheet', 'ledger', 'periodic', 'wagers', 'roster', 'referral-map', 'bonus', 'referrals', 'load', 'weekly'];

// Node built-ins the browser must never reach. If a code path tries, it should
// say so loudly rather than fail somewhere confusing.
const STUBS = ['fs', 'path', 'zlib'];

function bundle() {
  const parts = [];
  parts.push('// Generated by tools/build-html.js — edit lib/*.js, not this file.');
  parts.push('const PEF = (function () {');
  parts.push('  const registry = {};');
  parts.push('  const cache = {};');
  parts.push('  function require(id) {');
  parts.push("    const key = id.replace(/^\\.\\//, '');");
  parts.push('    if (cache[key]) return cache[key].exports;');
  parts.push('    const factory = registry[key];');
  parts.push('    if (!factory) throw new Error("Module not available in the browser build: " + id);');
  parts.push('    const module = { exports: {} };');
  parts.push('    cache[key] = module;');
  parts.push('    factory(module, module.exports, require);');
  parts.push('    return module.exports;');
  parts.push('  }');

  for (const stub of STUBS) {
    parts.push(`  registry[${JSON.stringify(stub)}] = function () {`);
    parts.push(`    throw new Error("The browser build cannot use Node's ${stub} module.");`);
    parts.push('  };');
  }

  for (const name of MODULES) {
    const source = fs.readFileSync(path.join(ROOT, 'lib', `${name}.js`), 'utf8');
    parts.push(`  registry[${JSON.stringify(name)}] = function (module, exports, require) {`);
    parts.push(source.replace(/^/gm, '    '));
    parts.push('  };');
  }

  parts.push('  return { require };');
  parts.push('})();');
  return parts.join('\n');
}

// The maintained referral list travels with the page, so the browser tool knows
// the same relationships the CLI does without anyone remembering to attach it.
function referralList() {
  const file = path.join(ROOT, 'data', 'referrals.csv');
  const text = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  return `const REFERRAL_LIST_CSV = ${JSON.stringify(text)};`;
}

function main() {
  const template = fs.readFileSync(path.join(ROOT, 'web', 'template.html'), 'utf8');
  for (const marker of ['/* __PEF_BUNDLE__ */', '/* __PEF_REFERRALS__ */']) {
    if (!template.includes(marker)) {
      throw new Error(`web/template.html is missing the ${marker} placeholder`);
    }
  }

  const html = template
    .replace('/* __PEF_BUNDLE__ */', () => bundle())
    .replace('/* __PEF_REFERRALS__ */', () => referralList());
  const outDir = path.join(ROOT, 'dist');
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, 'weekly-report.html');
  fs.writeFileSync(outFile, html);

  const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
  const listed = (html.match(/const REFERRAL_LIST_CSV = "(.*)"/) || ['', '']).length;
  console.log(`Built ${path.relative(ROOT, outFile)} (${kb} KB, ${MODULES.length} modules, `
    + `referral list ${listed ? 'embedded' : 'absent'})`);
}

main();
